name: boxy_gallery
description: Examples for the boxy package.
version: 1.0.0
author: Andre Lipke <andre.lipke@gmail.com>
homepage: https://github.com/PixelToast/flutter-boxy

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  boxy: ^1.0.0
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^3.4.4995
  rxdart: ^0.23.1
  tuple: ^1.0.3
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  boxy:
    path: ../