name: boxy
description: Layout made simple. Overcomes many limitations by the framework regarding layout
version: 2.0.0
homepage: https://github.com/PixelToast/flutter-boxy

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter