name: boxy
description: Provides widgets and utilities that enable you to create custom layouts with minimal boilerplate.
version: 1.2.0+1
homepage: https://github.com/PixelToast/flutter-boxy

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter