version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

commands:
  install_flutter:
    steps:
      - run:
          name: "Install Flutter"
          command: |-
            touch $BASH_ENV
            curl -o- https://puro.dev/install.sh | PURO_VERSION="master" bash
            source $BASH_ENV
            puro flutter --version

  pub_get:
    steps:
      - run:
          name: "Pub Get"
          command: |-
            cd boxy
            flutter pub get

  format:
    steps:
      - run:
          name: "Format"
          command: |-
            dart format --set-exit-if-changed .

  analyze:
    steps:
      - run:
          name: "Analyze"
          command: |-
            dart analyze .

  test:
    steps:
      - run:
          name: "Test"
          command: |-
            cd boxy
            flutter test -r expanded

  test_all:
    steps:
      - checkout
      - pub_get
      - format
      - analyze
      - test

jobs:
  linux_tests:
    docker:
      - image: cimg/base:stable
    steps:
      - install_flutter
      - test_all

  build_website:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "93:cb:27:b3:11:c7:99:17:7f:95:43:c9:89:fc:8c:be"
      - run: |-
          git clone https://github.com/PixelToast/mkdocs-material-insiders.git
          pip install ./mkdocs-material-insiders
          cd website
          export PYTHONPATH=`pwd`
          mkdocs build
      - aws-s3/sync:
          from: website/site/
          to: s3://boxy-website
      - run: aws cloudfront create-invalidation --distribution-id $BOXY_CF_DISTRIBUTION --paths "/*"

workflows:
  master:
    jobs:
      - build_website
    when:
      equal: [ "master", << pipeline.git.branch >> ]
  tests:
    jobs:
      - linux_tests
