name: boxy
description: Overcome limitations of built-in layouts, advanced flex, custom multi-child layouts, slivers, and more!
version: 2.0.9
homepage: https://github.com/PixelToast/boxy
documentation: https://boxy.wiki

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
