name: boxy_gallery
description: Examples for the boxy package.
version: 1.0.0
homepage: https://github.com/pingbird/boxy

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  boxy: ^2.0.6+2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.5955-rc.1
  rxdart: ^0.26.0
  tuple: ^2.0.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  boxy:
    path: ../
